export const roles = [
  { name: "Seller", id: "1", type: "seller" },
  { name: "Buyer", id: "2", type: "buyer" },
];

export const category = [
  { id: 1, label: "Fruits", value: "Fruits" },
  { id: 2, label: "Vegetables", value: "Vegetables" },
  { id: 3, label: "Fertilizers", value: "Fertilizers" },
  {
    id: 4,
    label: "Fiber & Oil Seed Crops",
    value: "Fiber & Oil Seed Crops",
  },
  { id: 5, label: "Grains & Cereals", value: "Grains & Cereals" },
  {
    id: 6,
    label: "Plant Pathology & Entomology",
    value: "Plant Pathology & Entomology",
  },
  { id: 7, label: "Seed Varieties", value: "Seed Varieties" },
  { id: 8, label: "Machinary & Tools", value: "Machinary & Tools" },
];

export const packagingType = [
  { id: 1, label: "Plastic Bags", value: "plasticBag" },
  { id: 2, label: "Cloth Bags", value: "clothBag" },
  { id: 3, label: "Burlap Bags", value: "burlapBags" },
  { id: 4, label: "Boxes / Crates", value: "boxesCrates" },
]

export const weightUnitType = [
  { id: 1, label: "Kg", value: "kg" },
  { id: 2, label: "Liter", value: "liter" },
  { id: 3, label: "Dozen", value: "dozen" },
  { id: 4, label: "Sankara", value: "sankara" },
]

export const yesNoOption = [
  { id: 1, label: "Yes", value: "yes" },
  { id: 2, label: "No", value: "no" },
]

export const taxOpt = [
  { id: 1, label: "Inclusive", value: "inclusive" },
  { id: 2, label: "Exclusive", value: "exclusive" },
]

export const shippingOption = [
  { id: 1, label: "Free", value: "free" },
  { id: 2, label: "Amount", value: "amount" },
]

export const seedTypeOption = [
  { id: 1, label: "Hybrid", value: "hybrid" },
  { id: 2, label: "Synthetic", value: "synthetic" },
  { id: 2, label: "Organic", value: "organic" },
]

export const seedRegionOption = [
  { id: 1, label: "Irrigated", value: "irrigated" },
  { id: 2, label: "Rainfed", value: "rainfed" },
  { id: 2, label: "Drought", value: "drought" },
]

export const machinaryToolsOption = [
  { id: 1, label: "Tool", value: "Tool" },
  { id: 2, label: "Machinary", value: "Machinary" },
]

export const toolCondition = [
  { id: 1, label: "New", value: "new" },
  { id: 2, label: "Used", value: "used" },
]


export const districtsOption = [
    "Attock",
    "Bahawalnagar",
    "Bahawalpur",
    "Bhakkar",
    "Chakwal",
    "Chiniot",
    "Dera Ghazi Khan",
    "Faisalabad",
    "Gujranwala",
    "Gujrat",
    "Hafizabad",
    "Jhang",
    "Jhelum",
    "Kasur",
    "Khanewal",
    "Khushab",
    "Lahore",
    "Layyah",
    "Lodhran",
    "Mandi Bahauddin",
    "Mianwali",
    "Multan",
    "Muzaffargarh",
    "Nankana Sahib",
    "Narowal",
    "Okara",
    "Pakpattan",
    "Rahim Yar Khan",
    "Rajanpur",
    "Rawalpindi",
    "Sahiwal",
    "Sargodha",
    "Sheikhupura",
    "Sialkot",
    "Toba Tek Singh",
    "Vehari",
    "Badin",
    "Dadu",
    "Ghotki",
    "Hyderabad",
    "Jacobabad",
    "Jamshoro",
    "Karachi Central",
    "Karachi East",
    "Karachi South",
    "Karachi West",
    "Kashmore",
    "Khairpur",
    "Larkana",
    "Matiari",
    "Mirpur Khas",
    "Naushahro Firoz",
    "Qambar Shahdadkot",
    "Sanghar",
    "Shikarpur",
    "Sukkur",
    "Tando Allahyar",
    "Tando Muhammad Khan",
    "Tharparkar",
    "Thatta",
    "Umerkot",
    "Abbottabad",
    "Bannu",
    "Batagram",
    "Buner",
    "Charsadda",
    "Chitral",
    "Dera Ismail Khan",
    "Hangu",
    "Haripur",
    "Karak",
    "Kohat",
    "Kohistan",
    "Lakki Marwat",
    "Lower Dir",
    "Malakand",
    "Mansehra",
    "Mardan",
    "Nowshera",
    "Peshawar",
    "Shangla",
    "Swabi",
    "Swat",
    "Tank",
    "Tor Ghar",
    "Upper Dir",
    "Awaran",
    "Barkhan",
    "Bolan",
    "Chagai",
    "Dera Bugti",
    "Gwadar",
    "Harnai",
    "Jafarabad",
    "Jhal Magsi",
    "Kalat",
    "Kech",
    "Kharan",
    "Khuzdar",
    "Killa Abdullah",
    "Killa Saifullah",
    "Kohlu",
    "Lasbela",
    "Loralai",
    "Mastung",
    "Musakhel",
    "Naseerabad",
    "Nushki",
    "Panjgur",
    "Pishin",
    "Quetta",
    "Sherani",
    "Sibi",
    "Sohbatpur",
    "Washuk",
    "Zhob",
    "Ziarat",
    "Astore",
    "Diamer",
    "Ghanche",
    "Gilgit",
    "Hunza",
    "Kharmang",
    "Nagar",
    "Shigar",
    "Shangla",
    "Skardu",
    "Bagh",
    "Bhimber",
    "Hattian",
    "Haveli",
    "Kotli",
    "Mirpur",
    "Muzaffarabad",
    "Neelum",
    "Poonch",
    "Sudhanoti"
]

export const tehsilOption ={
  "Punjab": [
    "Attock",
    "Bahawalnagar",
    "Bahawalpur",
    "Bhakkar",
    "Chakwal",
    "Chiniot",
    "Dera Ghazi Khan",
    "Faisalabad",
    "Gujranwala",
    "Gujrat",
    "Hafizabad",
    "Jhang",
    "Jhelum",
    "Kasur",
    "Khanewal",
    "Khushab",
    "Lahore",
    "Layyah",
    "Lodhran",
    "Mandi Bahauddin",
    "Mianwali",
    "Multan",
    "Muzaffargarh",
    "Nankana Sahib",
    "Narowal",
    "Okara",
    "Pakpattan",
    "Rahim Yar Khan",
    "Rajanpur",
    "Rawalpindi",
    "Sahiwal",
    "Sargodha",
    "Sheikhupura",
    "Sialkot",
    "Toba Tek Singh",
    "Vehari"
  ],
  "Sindh": [
    "Badin",
    "Dadu",
    "Ghotki",
    "Hyderabad",
    "Jacobabad",
    "Jamshoro",
    "Karachi Central",
    "Karachi East",
    "Karachi South",
    "Karachi West",
    "Kashmore",
    "Khairpur",
    "Larkana",
    "Matiari",
    "Mirpur Khas",
    "Naushahro Firoz",
    "Qambar Shahdadkot",
    "Sanghar",
    "Shikarpur",
    "Sukkur",
    "Tando Allahyar",
    "Tando Muhammad Khan",
    "Tharparkar",
    "Thatta",
    "Umerkot"
  ],
  "Khyber Pakhtunkhwa": [
    "Abbottabad",
    "Bannu",
    "Batagram",
    "Buner",
    "Charsadda",
    "Chitral",
    "Dera Ismail Khan",
    "Hangu",
    "Haripur",
    "Karak",
    "Kohat",
    "Kohistan",
    "Lakki Marwat",
    "Lower Dir",
    "Malakand",
    "Mansehra",
    "Mardan",
    "Nowshera",
    "Peshawar",
    "Shangla",
    "Swabi",
    "Swat",
    "Tank",
    "Tor Ghar",
    "Upper Dir"
  ],
  "Balochistan": [
    "Awaran",
    "Barkhan",
    "Bolan",
    "Chagai",
    "Dera Bugti",
    "Gwadar",
    "Harnai",
    "Jafarabad",
    "Jhal Magsi",
    "Kalat",
    "Kech",
    "Kharan",
    "Khuzdar",
    "Killa Abdullah",
    "Killa Saifullah",
    "Kohlu",
    "Lasbela",
    "Loralai",
    "Mastung",
    "Musakhel",
    "Naseerabad",
    "Nushki",
    "Panjgur",
    "Pishin",
    "Quetta",
    "Sherani",
    "Sibi",
    "Sohbatpur",
    "Washuk",
    "Zhob",
    "Ziarat"
  ],
  "Gilgit-Baltistan": [
    "Astore",
    "Diamer",
    "Ghanche",
    "Gilgit",
    "Hunza",
    "Kharmang",
    "Nagar",
    "Shigar",
    "Shangla",
    "Skardu"
  ],
  "Azad Jammu and Kashmir": [
    "Bagh",
    "Bhimber",
    "Hattian",
    "Haveli",
    "Kotli",
    "Mirpur",
    "Muzaffarabad",
    "Neelum",
    "Poonch",
    "Sudhanoti"
  ]
}

