export const roles = [
  { name: "Seller", id: "1", type: "seller" },
  { name: "Buyer", id: "2", type: "buyer" },
];

export const category = [
  { id: 1, label: "Fruits", value: "Fruits" },
  { id: 2, label: "Vegetables", value: "Vegetables" },
  { id: 3, label: "Fertilizers", value: "Fertilizers" },
  {
    id: 4,
    label: "Fiber & Oil Seed Crops",
    value: "Fiber & Oil Seed Crops",
  },
  { id: 5, label: "Grains & Cereals", value: "Grains & Cereals" },
  {
    id: 6,
    label: "Plant Pathology & Entomology",
    value: "Plant Pathology & Entomology",
  },
  { id: 7, label: "Seed Varieties", value: "Seed Varieties" },
  { id: 8, label: "Machinary & Tools", value: "Machinary & Tools" },
];

export const packagingType = [
  { id: 1, label: "Plastic Bags", value: "plasticBag" },
  { id: 2, label: "Cloth Bags", value: "clothBag" },
  { id: 3, label: "Burlap Bags", value: "burlapBags" },
  { id: 4, label: "Boxes / Crates", value: "boxesCrates" },
]

export const weightUnitType = [
  { id: 1, label: "Kg", value: "kg" },
  { id: 2, label: "Liter", value: "liter" },
  { id: 3, label: "Dozen", value: "dozen" },
  { id: 4, label: "Sankara", value: "sankara" },
]

export const yesNoOption = [
  { id: 1, label: "Yes", value: "yes" },
  { id: 2, label: "No", value: "no" },
]

export const taxOpt = [
  { id: 1, label: "Inclusive", value: "inclusive" },
  { id: 2, label: "Exclusive", value: "exclusive" },
]

export const shippingOption = [
  { id: 1, label: "Free", value: "free" },
  { id: 2, label: "Amount", value: "amount" },
]

export const seedTypeOption = [
  { id: 1, label: "Hybrid", value: "hybrid" },
  { id: 2, label: "Synthetic", value: "synthetic" },
  { id: 2, label: "Organic", value: "organic" },
]

export const seedRegionOption = [
  { id: 1, label: "Irrigated", value: "irrigated" },
  { id: 2, label: "Rainfed", value: "rainfed" },
  { id: 2, label: "Drought", value: "drought" },
]

export const machinaryToolsOption = [
  { id: 1, label: "Tool", value: "Tool" },
  { id: 2, label: "Machinary", value: "Machinary" },
]

export const toolCondition = [
  { id: 1, label: "New", value: "new" },
  { id: 2, label: "Used", value: "used" },
]


export const districtsOption = [
  { label: "Attock", value: "Attock" },
  { label: "Bahawalnagar", value: "Bahawalnagar" },
  { label: "Bahawalpur", value: "Bahawalpur" },
  { label: "Bhakkar", value: "Bhakkar" },
  { label: "Chakwal", value: "Chakwal" },
  { label: "Chiniot", value: "Chiniot" },
  { label: "Dera Ghazi Khan", value: "Dera Ghazi Khan" },
  { label: "Faisalabad", value: "Faisalabad" },
  { label: "Gujranwala", value: "Gujranwala" },
  { label: "Gujrat", value: "Gujrat" },
  { label: "Hafizabad", value: "Hafizabad" },
  { label: "Jhang", value: "Jhang" },
  { label: "Jhelum", value: "Jhelum" },
  { label: "Kasur", value: "Kasur" },
  { label: "Khanewal", value: "Khanewal" },
  { label: "Khushab", value: "Khushab" },
  { label: "Lahore", value: "Lahore" },
  { label: "Layyah", value: "Layyah" },
  { label: "Lodhran", value: "Lodhran" },
  { label: "Mandi Bahauddin", value: "Mandi Bahauddin" },
  { label: "Mianwali", value: "Mianwali" },
  { label: "Multan", value: "Multan" },
  { label: "Muzaffargarh", value: "Muzaffargarh" },
  { label: "Nankana Sahib", value: "Nankana Sahib" },
  { label: "Narowal", value: "Narowal" },
  { label: "Okara", value: "Okara" },
  { label: "Pakpattan", value: "Pakpattan" },
  { label: "Rahim Yar Khan", value: "Rahim Yar Khan" },
  { label: "Rajanpur", value: "Rajanpur" },
  { label: "Rawalpindi", value: "Rawalpindi" },
  { label: "Sahiwal", value: "Sahiwal" },
  { label: "Sargodha", value: "Sargodha" },
  { label: "Sheikhupura", value: "Sheikhupura" },
  { label: "Sialkot", value: "Sialkot" },
  { label: "Toba Tek Singh", value: "Toba Tek Singh" },
  { label: "Vehari", value: "Vehari" },
  { label: "Badin", value: "Badin" },
  { label: "Dadu", value: "Dadu" },
  { label: "Ghotki", value: "Ghotki" },
  { label: "Hyderabad", value: "Hyderabad" },
  { label: "Jacobabad", value: "Jacobabad" },
  { label: "Jamshoro", value: "Jamshoro" },
  { label: "Karachi Central", value: "Karachi Central" },
  { label: "Karachi East", value: "Karachi East" },
  { label: "Karachi South", value: "Karachi South" },
  { label: "Karachi West", value: "Karachi West" },
  { label: "Kashmore", value: "Kashmore" },
  { label: "Khairpur", value: "Khairpur" },
  { label: "Larkana", value: "Larkana" },
  { label: "Matiari", value: "Matiari" },
  { label: "Mirpur Khas", value: "Mirpur Khas" },
  { label: "Naushahro Firoz", value: "Naushahro Firoz" },
  { label: "Qambar Shahdadkot", value: "Qambar Shahdadkot" },
  { label: "Sanghar", value: "Sanghar" },
  { label: "Shikarpur", value: "Shikarpur" },
  { label: "Sukkur", value: "Sukkur" },
  { label: "Tando Allahyar", value: "Tando Allahyar" },
  { label: "Tando Muhammad Khan", value: "Tando Muhammad Khan" },
  { label: "Tharparkar", value: "Tharparkar" },
  { label: "Thatta", value: "Thatta" },
  { label: "Umerkot", value: "Umerkot" },
  { label: "Abbottabad", value: "Abbottabad" },
  { label: "Bannu", value: "Bannu" },
  { label: "Batagram", value: "Batagram" },
  { label: "Buner", value: "Buner" },
  { label: "Charsadda", value: "Charsadda" },
  { label: "Chitral", value: "Chitral" },
  { label: "Dera Ismail Khan", value: "Dera Ismail Khan" },
  { label: "Hangu", value: "Hangu" },
  { label: "Haripur", value: "Haripur" },
  { label: "Karak", value: "Karak" },
  { label: "Kohat", value: "Kohat" },
  { label: "Kohistan", value: "Kohistan" },
  { label: "Lakki Marwat", value: "Lakki Marwat" },
  { label: "Lower Dir", value: "Lower Dir" },
  { label: "Malakand", value: "Malakand" },
  { label: "Mansehra", value: "Mansehra" },
  { label: "Mardan", value: "Mardan" },
  { label: "Nowshera", value: "Nowshera" },
  { label: "Peshawar", value: "Peshawar" },
  { label: "Shangla", value: "Shangla" },
  { label: "Swabi", value: "Swabi" },
  { label: "Swat", value: "Swat" },
  { label: "Tank", value: "Tank" },
  { label: "Tor Ghar", value: "Tor Ghar" },
  { label: "Upper Dir", value: "Upper Dir" },
  { label: "Awaran", value: "Awaran" },
  { label: "Barkhan", value: "Barkhan" },
  { label: "Bolan", value: "Bolan" },
  { label: "Chagai", value: "Chagai" },
  { label: "Dera Bugti", value: "Dera Bugti" },
  { label: "Gwadar", value: "Gwadar" },
  { label: "Harnai", value: "Harnai" },
  { label: "Jafarabad", value: "Jafarabad" },
  { label: "Jhal Magsi", value: "Jhal Magsi" },
  { label: "Kalat", value: "Kalat" },
  { label: "Kech", value: "Kech" },
  { label: "Kharan", value: "Kharan" },
  { label: "Khuzdar", value: "Khuzdar" },
  { label: "Killa Abdullah", value: "Killa Abdullah" },
  { label: "Killa Saifullah", value: "Killa Saifullah" },
  { label: "Kohlu", value: "Kohlu" },
  { label: "Lasbela", value: "Lasbela" },
  { label: "Loralai", value: "Loralai" },
  { label: "Mastung", value: "Mastung" },
  { label: "Musakhel", value: "Musakhel" },
  { label: "Naseerabad", value: "Naseerabad" },
  { label: "Nushki", value: "Nushki" },
  { label: "Panjgur", value: "Panjgur" },
  { label: "Pishin", value: "Pishin" },
  { label: "Quetta", value: "Quetta" },
  { label: "Sherani", value: "Sherani" },
  { label: "Sibi", value: "Sibi" },
  { label: "Sohbatpur", value: "Sohbatpur" },
  { label: "Washuk", value: "Washuk" },
  { label: "Zhob", value: "Zhob" },
  { label: "Ziarat", value: "Ziarat" },
  { label: "Astore", value: "Astore" },
  { label: "Diamer", value: "Diamer" },
  { label: "Ghanche", value: "Ghanche" },
  { label: "Gilgit", value: "Gilgit" },
  { label: "Hunza", value: "Hunza" },
  { label: "Kharmang", value: "Kharmang" },
  { label: "Nagar", value: "Nagar" },
  { label: "Shigar", value: "Shigar" },
  { label: "Shangla", value: "Shangla" },
  { label: "Skardu", value: "Skardu" },
  { label: "Bagh", value: "Bagh" },
  { label: "Bhimber", value: "Bhimber" },
  { label: "Hattian", value: "Hattian" },
  { label: "Haveli", value: "Haveli" },
  { label: "Kotli", value: "Kotli" },
  { label: "Mirpur", value: "Mirpur" },
  { label: "Muzaffarabad", value: "Muzaffarabad" },
  { label: "Neelum", value: "Neelum" },
  { label: "Poonch", value: "Poonch" },
  { label: "Sudhanoti", value: "Sudhanoti" }
];


export const citiesOptions = [
  { label: "Islamabad", value: "Islamabad" },
  { label: "Ahmed Nager", value: "Ahmed Nager" },
  { label: "Ahmadpur East", value: "Ahmadpur East" },
  { label: "Ali Khan", value: "Ali Khan" },
  { label: "Alipur", value: "Alipur" },
  { label: "Arifwala", value: "Arifwala" },
  { label: "Attock", value: "Attock" },
  { label: "Bhera", value: "Bhera" },
  { label: "Bhalwal", value: "Bhalwal" },
  { label: "Bahawalnagar", value: "Bahawalnagar" },
  { label: "Bahawalpur", value: "Bahawalpur" },
  { label: "Bhakkar", value: "Bhakkar" },
  { label: "Burewala", value: "Burewala" },
  { label: "Chillianwala", value: "Chillianwala" },
  { label: "Chakwal", value: "Chakwal" },
  { label: "Chichawatni", value: "Chichawatni" },
  { label: "Chiniot", value: "Chiniot" },
  { label: "Chishtian", value: "Chishtian" },
  { label: "Daska", value: "Daska" },
  { label: "Darya Khan", value: "Darya Khan" },
  { label: "Dera Ghazi", value: "Dera Ghazi" },
  { label: "Dhaular", value: "Dhaular" },
  { label: "Dina", value: "Dina" },
  { label: "Dinga", value: "Dinga" },
  { label: "Dipalpur", value: "Dipalpur" },
  { label: "Faisalabad", value: "Faisalabad" },
  { label: "Fateh Jhang", value: "Fateh Jhang" },
  { label: "Ghakhar Mandi", value: "Ghakhar Mandi" },
  { label: "Gojra", value: "Gojra" },
  { label: "Gujranwala", value: "Gujranwala" },
  { label: "Gujrat", value: "Gujrat" },
  { label: "Gujar Khan", value: "Gujar Khan" },
  { label: "Hafizabad", value: "Hafizabad" },
  { label: "Haroonabad", value: "Haroonabad" },
  { label: "Hasilpur", value: "Hasilpur" },
  { label: "Haveli", value: "Haveli" },
  { label: "Lakha", value: "Lakha" },
  { label: "Jalalpur", value: "Jalalpur" },
  { label: "Jattan", value: "Jattan" },
  { label: "Jampur", value: "Jampur" },
  { label: "Jaranwala", value: "Jaranwala" },
  { label: "Jhang", value: "Jhang" },
  { label: "Jhelum", value: "Jhelum" },
  { label: "Kalabagh", value: "Kalabagh" },
  { label: "Karor Lal", value: "Karor Lal" },
  { label: "Kasur", value: "Kasur" },
  { label: "Kamalia", value: "Kamalia" },
  { label: "Kamoke", value: "Kamoke" },
  { label: "Khanewal", value: "Khanewal" },
  { label: "Khanpur", value: "Khanpur" },
  { label: "Kharian", value: "Kharian" },
  { label: "Khushab", value: "Khushab" },
  { label: "Kot Adu", value: "Kot Adu" },
  { label: "Jauharabad", value: "Jauharabad" },
  { label: "Lahore", value: "Lahore" },
  { label: "Lalamusa", value: "Lalamusa" },
  { label: "Layyah", value: "Layyah" },
  { label: "Liaquat Pur", value: "Liaquat Pur" },
  { label: "Lodhran", value: "Lodhran" },
  { label: "Malakwal", value: "Malakwal" },
  { label: "Mamoori", value: "Mamoori" },
  { label: "Mailsi", value: "Mailsi" },
  { label: "Mandi Bahauddin", value: "Mandi Bahauddin" },
  { label: "Mian Channu", value: "Mian Channu" },
  { label: "Mianwali", value: "Mianwali" },
  { label: "Multan", value: "Multan" },
  { label: "Murree", value: "Murree" },
  { label: "Muridke", value: "Muridke" },
  { label: "Mianwali Bangla", value: "Mianwali Bangla" },
  { label: "Muzaffargarh", value: "Muzaffargarh" },
  { label: "Narowal", value: "Narowal" },
  { label: "Okara", value: "Okara" },
  { label: "Renala Khurd", value: "Renala Khurd" },
  { label: "Pakpattan", value: "Pakpattan" },
  { label: "Pattoki", value: "Pattoki" },
  { label: "Pir Mahal", value: "Pir Mahal" },
  { label: "Qaimpur", value: "Qaimpur" },
  { label: "Qila Didar", value: "Qila Didar" },
  { label: "Rabwah", value: "Rabwah" },
  { label: "Raiwind", value: "Raiwind" },
  { label: "Rajanpur", value: "Rajanpur" },
  { label: "Rahim Yar", value: "Rahim Yar" },
  { label: "Rawalpindi", value: "Rawalpindi" },
  { label: "Sadiqabad", value: "Sadiqabad" },
  { label: "Safdarabad", value: "Safdarabad" },
  { label: "Sahiwal", value: "Sahiwal" },
  { label: "Sangla Hill", value: "Sangla Hill" },
  { label: "Sarai Alamgir", value: "Sarai Alamgir" },
  { label: "Sargodha", value: "Sargodha" },
  { label: "Shakargarh", value: "Shakargarh" },
  { label: "Sheikhupura", value: "Sheikhupura" },
  { label: "Sialkot", value: "Sialkot" },
  { label: "Sohawa", value: "Sohawa" },
  { label: "Soianwala", value: "Soianwala" },
  { label: "Siranwali", value: "Siranwali" },
  { label: "Talagang", value: "Talagang" },
  { label: "Taxila", value: "Taxila" },
  { label: "Toba Tek", value: "Toba Tek" },
  { label: "Vehari", value: "Vehari" },
  { label: "Wah Cantonment", value: "Wah Cantonment" },
  { label: "Wazirabad", value: "Wazirabad" },
  { label: "Badin", value: "Badin" },
  { label: "Bhirkan", value: "Bhirkan" },
  { label: "Rajo Khanani", value: "Rajo Khanani" },
  { label: "Chak", value: "Chak" },
  { label: "Dadu", value: "Dadu" },
  { label: "Digri", value: "Digri" },
  { label: "Diplo", value: "Diplo" },
  { label: "Dokri", value: "Dokri" },
  { label: "Ghotki", value: "Ghotki" },
  { label: "Haala", value: "Haala" },
  { label: "Hyderabad", value: "Hyderabad" },
  { label: "Islamkot", value: "Islamkot" },
  { label: "Jacobabad", value: "Jacobabad" },
  { label: "Jamshoro", value: "Jamshoro" },
  { label: "Jungshahi", value: "Jungshahi" },
  { label: "Kandhkot", value: "Kandhkot" },
  { label: "Kandiaro", value: "Kandiaro" },
  { label: "Karachi", value: "Karachi" },
  { label: "Kashmore", value: "Kashmore" },
  { label: "Keti Bandar", value: "Keti Bandar" },
  { label: "Khairpur", value: "Khairpur" },
  { label: "Kotri", value: "Kotri" },
  { label: "Larkana", value: "Larkana" },
  { label: "Matiari", value: "Matiari" },
  { label: "Mehar", value: "Mehar" },
  { label: "Mirpur Khas", value: "Mirpur Khas" },
  { label: "Mithani", value: "Mithani" },
  { label: "Mithi", value: "Mithi" },
  { label: "Mehrabpur", value: "Mehrabpur" },
  { label: "Moro", value: "Moro" },
  { label: "Nagarparkar", value: "Nagarparkar" },
  { label: "Naudero", value: "Naudero" },
  { label: "Naushahro Feroze", value: "Naushahro Feroze" },
  { label: "Naushara", value: "Naushara" },
  { label: "Nawabshah", value: "Nawabshah" },
  { label: "Nazimabad", value: "Nazimabad" },
  { label: "Qambar", value: "Qambar" },
  { label: "Qasimabad", value: "Qasimabad" },
  { label: "Ranipur", value: "Ranipur" },
  { label: "Ratodero", value: "Ratodero" },
  { label: "Rohri", value: "Rohri" },
  { label: "Sakrand", value: "Sakrand" },
  { label: "Sanghar", value: "Sanghar" },
  { label: "Shahbandar", value: "Shahbandar" },
  { label: "Shahdadkot", value: "Shahdadkot" },
  { label: "Shahdadpur", value: "Shahdadpur" },
  { label: "Shahpur Chakar", value: "Shahpur Chakar" },
  { label: "Shikarpaur", value: "Shikarpaur" },
  { label: "Sukkur", value: "Sukkur" },
  { label: "Tangwani", value: "Tangwani" },
  { label: "Tando Adam", value: "Tando Adam" },
  { label: "Tando Allahyar", value: "Tando Allahyar" },
  { label: "Tando Muhammad", value: "Tando Muhammad" },
  { label: "Thatta", value: "Thatta" },
  { label: "Umerkot", value: "Umerkot" },
  { label: "Warah", value: "Warah" },
  { label: "Abbottabad", value: "Abbottabad" },
  { label: "Adezai", value: "Adezai" },
  { label: "Alpuri", value: "Alpuri" },
  { label: "Akora Khattak", value: "Akora Khattak" },
  { label: "Ayubia", value: "Ayubia" },
  { label: "Banda Daud", value: "Banda Daud" },
  { label: "Bannu", value: "Bannu" },
  { label: "Batkhela", value: "Batkhela" },
  { label: "Battagram", value: "Battagram" },
  { label: "Birote", value: "Birote" },
  { label: "Chakdara", value: "Chakdara" },
  { label: "Charsadda", value: "Charsadda" },
  { label: "Chitral", value: "Chitral" },
  { label: "Daggar", value: "Daggar" },
  { label: "Dargai", value: "Dargai" },
  { label: "Darya Khan", value: "Darya Khan" },
  { label: "Dera Ismail", value: "Dera Ismail" },
  { label: "Doaba", value: "Doaba" },
  { label: "Dir", value: "Dir" },
  { label: "Drosh", value: "Drosh" },
  { label: "Hangu", value: "Hangu" },
  { label: "Haripur", value: "Haripur" },
  { label: "Karak", value: "Karak" },
  { label: "Kohat", value: "Kohat" },
  { label: "Kulachi", value: "Kulachi" },
  { label: "Lakki Marwat", value: "Lakki Marwat" },
  { label: "Latamber", value: "Latamber" },
  { label: "Madyan", value: "Madyan" },
  { label: "Mansehra", value: "Mansehra" },
  { label: "Mardan", value: "Mardan" },
  { label: "Mastuj", value: "Mastuj" },
  { label: "Mingora", value: "Mingora" },
  { label: "Nowshera", value: "Nowshera" },
  { label: "Paharpur", value: "Paharpur" },
  { label: "Pabbi", value: "Pabbi" },
  { label: "Peshawar", value: "Peshawar" },
  { label: "Saidu Sharif", value: "Saidu Sharif" },
  { label: "Shorkot", value: "Shorkot" },
  { label: "Shewa Adda", value: "Shewa Adda" },
  { label: "Swabi", value: "Swabi" },
  { label: "Swat", value: "Swat" },
  { label: "Tangi", value: "Tangi" },
  { label: "Tank", value: "Tank" },
  { label: "Thall", value: "Thall" },
  { label: "Timergara", value: "Timergara" },
  { label: "Tordher", value: "Tordher" },
  { label: "Awaran", value: "Awaran" },
  { label: "Barkhan", value: "Barkhan" },
  { label: "Chagai", value: "Chagai" },
  { label: "Dera Bugti", value: "Dera Bugti" },
  { label: "Gwadar", value: "Gwadar" },
  { label: "Harnai", value: "Harnai" },
  { label: "Jafarabad", value: "Jafarabad" },
  { label: "Jhal Magsi", value: "Jhal Magsi" },
  { label: "Kacchi", value: "Kacchi" },
  { label: "Kalat", value: "Kalat" },
  { label: "Kech", value: "Kech" },
  { label: "Kharan", value: "Kharan" },
  { label: "Khuzdar", value: "Khuzdar" },
  { label: "Killa Abdullah", value: "Killa Abdullah" },
  { label: "Killa Saifullah", value: "Killa Saifullah" },
  { label: "Kohlu", value: "Kohlu" },
  { label: "Lasbela", value: "Lasbela" },
  { label: "Lehri", value: "Lehri" },
  { label: "Loralai", value: "Loralai" },
  { label: "Mastung", value: "Mastung" },
  { label: "Musakhel", value: "Musakhel" },
  { label: "Nasirabad", value: "Nasirabad" },
  { label: "Nushki", value: "Nushki" },
  { label: "Panjgur", value: "Panjgur" },
  { label: "Pishin valley", value: "Pishin valley" },
  { label: "Quetta", value: "Quetta" },
  { label: "Sherani", value: "Sherani" },
  { label: "Sibi", value: "Sibi" },
  { label: "Sohbatpur", value: "Sohbatpur" },
  { label: "Washuk", value: "Washuk" },
  { label: "Zhob", value: "Zhob" },
  { label: "Ziarat", value: "Ziarat" }
];


export const tehsilsOption = [
    { label: "Islamabad", value: "Islamabad" },
    { label: "Ahmed Nager Chatha", value: "Ahmed Nager Chatha" },
    { label: "Ahmedpur East", value: "Ahmedpur East" },
    { label: "Ali Khan Abad", value: "Ali Khan Abad" },
    { label: "Alipur", value: "Alipur" },
    { label: "Arifwala", value: "Arifwala" },
    { label: "Attock", value: "Attock" },
    { label: "Bhera", value: "Bhera" },
    { label: "Bhalwal", value: "Bhalwal" },
    { label: "Bahawalnagar", value: "Bahawalnagar" },
    { label: "Bahawalpur", value: "Bahawalpur" },
    { label: "Bhakkar", value: "Bhakkar" },
    { label: "Burewala", value: "Burewala" },
    { label: "Chillianwala", value: "Chillianwala" },
    { label: "Chakwal", value: "Chakwal" },
    { label: "Chichawatni", value: "Chichawatni" },
    { label: "Chiniot", value: "Chiniot" },
    { label: "Chishtian", value: "Chishtian" },
    { label: "Daska", value: "Daska" },
    { label: "Darya Khan", value: "Darya Khan" },
    { label: "Dera Ghazi Khan", value: "Dera Ghazi Khan" },
    { label: "Dhaular", value: "Dhaular" },
    { label: "Dina", value: "Dina" },
    { label: "Dinga", value: "Dinga" },
    { label: "Dipalpur", value: "Dipalpur" },
    { label: "Faisalabad", value: "Faisalabad" },
    { label: "Fateh Jang", value: "Fateh Jang" },
    { label: "Ghakhar Mandi", value: "Ghakhar Mandi" },
    { label: "Gojra", value: "Gojra" },
    { label: "Gujranwala", value: "Gujranwala" },
    { label: "Gujrat", value: "Gujrat" },
    { label: "Gujar Khan", value: "Gujar Khan" },
    { label: "Hafizabad", value: "Hafizabad" },
    { label: "Haroonabad", value: "Haroonabad" },
    { label: "Hasilpur", value: "Hasilpur" },
    { label: "Haveli Lakha", value: "Haveli Lakha" },
    { label: "Jalalpur Jattan", value: "Jalalpur Jattan" },
    { label: "Jampur", value: "Jampur" },
    { label: "Jaranwala", value: "Jaranwala" },
    { label: "Jhang", value: "Jhang" },
    { label: "Jhelum", value: "Jhelum" },
    { label: "Kalabagh", value: "Kalabagh" },
    { label: "Karor Lal", value: "Karor Lal" },
    { label: "Kasur", value: "Kasur" },
    { label: "Kamalia", value: "Kamalia" },
    { label: "Kamoke", value: "Kamoke" },
    { label: "Khanewal", value: "Khanewal" },
    { label: "Khanpur", value: "Khanpur" },
    { label: "Kharian", value: "Kharian" },
    { label: "Khushab", value: "Khushab" },
    { label: "Kot Adu", value: "Kot Adu" },
    { label: "Jauharabad", value: "Jauharabad" },
    { label: "Lahore", value: "Lahore" },
    { label: "Lalamusa", value: "Lalamusa" },
    { label: "Layyah", value: "Layyah" },
    { label: "Liaquat Pur", value: "Liaquat Pur" },
    { label: "Lodhran", value: "Lodhran" },
    { label: "Malakwal", value: "Malakwal" },
    { label: "Mamoori", value: "Mamoori" },
    { label: "Mailsi", value: "Mailsi" },
    { label: "Mandi Bahauddin", value: "Mandi Bahauddin" },
    { label: "Mian Channu", value: "Mian Channu" },
    { label: "Mianwali", value: "Mianwali" },
    { label: "Multan", value: "Multan" },
    { label: "Murree", value: "Murree" },
    { label: "Muridke", value: "Muridke" },
    { label: "Mianwali Bangla", value: "Mianwali Bangla" },
    { label: "Muzaffargarh", value: "Muzaffargarh" },
    { label: "Narowal", value: "Narowal" },
    { label: "Okara", value: "Okara" },
    { label: "Renala Khurd", value: "Renala Khurd" },
    { label: "Pakpattan", value: "Pakpattan" },
    { label: "Pattoki", value: "Pattoki" },
    { label: "Pir Mahal", value: "Pir Mahal" },
    { label: "Qaimpur", value: "Qaimpur" },
    { label: "Qila Didar Singh", value: "Qila Didar Singh" },
    { label: "Rabwah", value: "Rabwah" },
    { label: "Raiwind", value: "Raiwind" },
    { label: "Rajanpur", value: "Rajanpur" },
    { label: "Rahim Yar Khan", value: "Rahim Yar Khan" },
    { label: "Rawalpindi", value: "Rawalpindi" },
    { label: "Sadiqabad", value: "Sadiqabad" },
    { label: "Safdarabad", value: "Safdarabad" },
    { label: "Sahiwal", value: "Sahiwal" },
    { label: "Sangla Hill", value: "Sangla Hill" },
    { label: "Sarai Alamgir", value: "Sarai Alamgir" },
    { label: "Sargodha", value: "Sargodha" },
    { label: "Shakargarh", value: "Shakargarh" },
    { label: "Sheikhupura", value: "Sheikhupura" },
    { label: "Sialkot", value: "Sialkot" },
    { label: "Sohawa", value: "Sohawa" },
    { label: "Soianwala", value: "Soianwala" },
    { label: "Siranwali", value: "Siranwali" },
    { label: "Talagang", value: "Talagang" },
    { label: "Taxila", value: "Taxila" },
    { label: "Toba Tek Singh", value: "Toba Tek Singh" },
    { label: "Vehari", value: "Vehari" },
    { label: "Wah Cantonment", value: "Wah Cantonment" },
    { label: "Wazirabad", value: "Wazirabad" },
    { label: "Badin", value: "Badin" },
    { label: "Bhirkan", value: "Bhirkan" },
    { label: "Rajo Khanani", value: "Rajo Khanani" },
    { label: "Chak", value: "Chak" },
    { label: "Dadu", value: "Dadu" },
    { label: "Digri", value: "Digri" },
    { label: "Diplo", value: "Diplo" },
    { label: "Dokri", value: "Dokri" },
    { label: "Ghotki", value: "Ghotki" },
    { label: "Haala", value: "Haala" },
    { label: "Hyderabad", value: "Hyderabad" },
    { label: "Islamkot", value: "Islamkot" },
    { label: "Jacobabad", value: "Jacobabad" },
    { label: "Jamshoro", value: "Jamshoro" },
    { label: "Jungshahi", value: "Jungshahi" },
    { label: "Kandhkot", value: "Kandhkot" },
    { label: "Kandiaro", value: "Kandiaro" },
    { label: "Karachi", value: "Karachi" },
    { label: "Kashmore", value: "Kashmore" },
    { label: "Keti Bandar", value: "Keti Bandar" },
    { label: "Khairpur", value: "Khairpur" },
    { label: "Kotri", value: "Kotri" },
    { label: "Larkana", value: "Larkana" },
    { label: "Matiari", value: "Matiari" },
    { label: "Mehar", value: "Mehar" },
    { label: "Mirpur Khas", value: "Mirpur Khas" },
    { label: "Mithani", value: "Mithani" },
    { label: "Mithi", value: "Mithi" },
    { label: "Mehrabpur", value: "Mehrabpur" },
    { label: "Moro", value: "Moro" },
    { label: "Nagarparkar", value: "Nagarparkar" },
    { label: "Naudero", value: "Naudero" },
    { label: "Naushahro Feroze", value: "Naushahro Feroze" },
    { label: "Naushara", value: "Naushara" },
    { label: "Nawabshah", value: "Nawabshah" },
    { label: "Nazimabad", value: "Nazimabad" },
    { label: "Qambar", value: "Qambar" },
    { label: "Qasimabad", value: "Qasimabad" },
    { label: "Ranipur", value: "Ranipur" },
    { label: "Ratodero", value: "Ratodero" },
    { label: "Rohri", value: "Rohri" },
    { label: "Sakrand", value: "Sakrand" },
    { label: "Sanghar", value: "Sanghar" },
    { label: "Shahbandar", value: "Shahbandar" },
    { label: "Shahdadkot", value: "Shahdadkot" },
    { label: "Shahdadpur", value: "Shahdadpur" },
    { label: "Shahpur Chakar", value: "Shahpur Chakar" },
    { label: "Shikarpaur", value: "Shikarpaur" },
    { label: "Sukkur", value: "Sukkur" },
    { label: "Tangwani", value: "Tangwani" },
    { label: "Tando Adam", value: "Tando Adam" },
    { label: "Tando Allahyar", value: "Tando Allahyar" },
    { label: "Tando Muhammad Khan", value: "Tando Muhammad Khan" },
    { label: "Thatta", value: "Thatta" },
    { label: "Umerkot", value: "Umerkot" },
    { label: "Warah", value: "Warah" },
    { label: "Abbottabad", value: "Abbottabad" },
    { label: "Adezai", value: "Adezai" },
    { label: "Alpuri", value: "Alpuri" },
    { label: "Akora Khattak", value: "Akora Khattak" },
    { label: "Ayubia", value: "Ayubia" },
    { label: "Banda Daud Shah", value: "Banda Daud Shah" },
    { label: "Bannu", value: "Bannu" },
    { label: "Batkhela", value: "Batkhela" },
    { label: "Battagram", value: "Battagram" },
    { label: "Birote", value: "Birote" },
    { label: "Chakdara", value: "Chakdara" },
    { label: "Charsadda", value: "Charsadda" },
    { label: "Chitral", value: "Chitral" },
    { label: "Daggar", value: "Daggar" },
    { label: "Dargai", value: "Dargai" },
    { label: "Darya Khan", value: "Darya Khan" },
    { label: "Dera Ismail Khan", value: "Dera Ismail Khan" },
    { label: "Doaba", value: "Doaba" },
    { label: "Dir", value: "Dir" },
    { label: "Drosh", value: "Drosh" },
    { label: "Hangu", value: "Hangu" },
    { label: "Haripur", value: "Haripur" },
    { label: "Karak", value: "Karak" },
    { label: "Kohat", value: "Kohat" },
    { label: "Kulachi", value: "Kulachi" },
    { label: "Lakki Marwat", value: "Lakki Marwat" },
    { label: "Latamber", value: "Latamber" },
    { label: "Madyan", value: "Madyan" },
    { label: "Mansehra", value: "Mansehra" },
    { label: "Mardan", value: "Mardan" },
    { label: "Mastuj", value: "Mastuj" },
    { label: "Mingora", value: "Mingora" },
    { label: "Nowshera", value: "Nowshera" },
    { label: "Paharpur", value: "Paharpur" },
    { label: "Pabbi", value: "Pabbi" },
    { label: "Peshawar", value: "Peshawar" },
    { label: "Saidu Sharif", value: "Saidu Sharif" },
    { label: "Shorkot", value: "Shorkot" },
    { label: "Shewa Adda", value: "Shewa Adda" },
    { label: "Swabi", value: "Swabi" },
    { label: "Swat", value: "Swat" },
    { label: "Tangi", value: "Tangi" },
    { label: "Tank", value: "Tank" },
    { label: "Thall", value: "Thall" },
    { label: "Timergara", value: "Timergara" },
    { label: "Tordher", value: "Tordher" },
    { label: "Awaran", value: "Awaran" },
    { label: "Barkhan", value: "Barkhan" },
    { label: "Chagai", value: "Chagai" },
    { label: "Dera Bugti", value: "Dera Bugti" },
    { label: "Gwadar", value: "Gwadar" },
    { label: "Harnai", value: "Harnai" },
    { label: "Jafarabad", value: "Jafarabad" },
    { label: "Jhal Magsi", value: "Jhal Magsi" },
    { label: "Kalat", value: "Kalat" },
    { label: "Kech", value: "Kech" },
    { label: "Kharan", value: "Kharan" },
    { label: "Khuzdar", value: "Khuzdar" },
    { label: "Killa Abdullah", value: "Killa Abdullah" },
    { label: "Killa Saifullah", value: "Killa Saifullah" },
    { label: "Kohlu", value: "Kohlu" },
    { label: "Lasbela", value: "Lasbela" },
    { label: "Lehri", value: "Lehri" },
    { label: "Loralai", value: "Loralai" },
    { label: "Mastung", value: "Mastung" },
    { label: "Musakhel", value: "Musakhel" },
    { label: "Nasirabad", value: "Nasirabad" },
    { label: "Nushki", value: "Nushki" },
    { label: "Panjgur", value: "Panjgur" },
    { label: "Pishin", value: "Pishin" },
    { label: "Quetta", value: "Quetta" },
    { label: "Sherani", value: "Sherani" },
    { label: "Sibi", value: "Sibi" },
    { label: "Sohbatpur", value: "Sohbatpur" },
    { label: "Washuk", value: "Washuk" },
    { label: "Zhob", value: "Zhob" },
    { label: "Ziarat", value: "Ziarat" },
    { label: "Astore", value: "Astore" },
    { label: "Diamer", value: "Diamer" },
    { label: "Ghanche", value: "Ghanche" },
    { label: "Gilgit", value: "Gilgit" },
    { label: "Hunza", value: "Hunza" },
    { label: "Kharmang", value: "Kharmang" },
    { label: "Nagar", value: "Nagar" },
    { label: "Shigar", value: "Shigar" },
    { label: "Shangla", value: "Shangla" },
    { label: "Skardu", value: "Skardu" },
    { label: "Bagh", value: "Bagh" },
    { label: "Bhimber", value: "Bhimber" },
    { label: "Hattian", value: "Hattian" },
    { label: "Haveli", value: "Haveli" },
    { label: "Kotli", value: "Kotli" },
    { label: "Mirpur", value: "Mirpur" },
    { label: "Muzaffarabad", value: "Muzaffarabad" },
    { label: "Neelum", value: "Neelum" },
    { label: "Poonch", value: "Poonch" },
    { label: "Sudhanoti", value: "Sudhanoti" }
]



